ALTER TABLE business_profiles ADD COLUMN IF NOT EXISTS ipn VARCHAR(20);
ALTER TABLE business_profiles ADD COLUMN IF NOT EXISTS mfo VARCHAR(10);
ALTER TABLE business_profiles ADD COLUMN IF NOT EXISTS certificate_number VARCHAR(255);

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS seller_tax_note TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS seller_mfo VARCHAR(10);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS seller_ipn VARCHAR(20);
